config/routes.rb
Rails.application.routes.draw do
  # 定期ジョブの管理画面のため追加
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'
  mount Sidekiq::Web, at: "/sidekiq"

  namespace :api do
    resources :products
  end

  resources :products

  resources :daily_aggregations

  root to: 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  # 論理削除のため追加
  acts_as_paranoid

  self.abstract_class = true
end

app/models/daily_aggregation.rb
class DailyAggregation < ApplicationRecord
  # バリデーション
  validates :date, presence: true
  validates :sort, presence: true
  validates :products_count, presence: true
  validates :products_ids, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  # HTTP通信のため追加
  include HTTParty
  base_uri 'localhost:3000'

  # 画像アップローダーの指定
  mount_base64_uploader :image, ImageUploader

  # バリデーション
  validates :image, presence: true
  validates :title, presence: true, length: { maximum: 100 }
  validates :description, presence: true, length: { maximum: 500 }
  validates :price, presence: true

  def get_data(uri)
    self.class.get(uri).parsed_response
  end

  def post_data(uri, options)
    self.class.post(uri, options)
  end

  def put_data(uri, options)
    self.class.put(uri, options)
  end

  def delete_data(uri)
    self.class.delete(uri)
  end
end

app/controllers/api/products_controller.rb
module Api
  class ProductsController < ApplicationController
    # CSRFの回避
    skip_before_action :verify_authenticity_token

    before_action :set_product, only: [:show, :update, :destroy]

    # 検索(全件取得)
    # GET /api/products
    def index
      @products = Product.all
      json_response(@products)
    end

    # 検索(取得)
    # GET /api/products/:id
    def show
      json_response(@product)
    end

    # 登録
    # POST /api/products
    def create
      @product = Product.create!(product_params)
      json_response(@product, :created)
    end

    # 変更
    # PUT /api/products/:id
    def update
      @product.update(product_params)
      head :no_content
    end

    # 削除
    # DELETE /api/products/:id
    def destroy
      @product.destroy
      head :no_content
    end

    private
      def product_params
        params.permit(:image, :title, :description, :price)
      end

      def set_product
        @product = Product.find(params[:id])
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Response
  include ExceptionHandler

  # 多言語対応のため追加
  before_action :set_locale

  def set_locale
    I18n.locale = locale
  end

  def locale
    @locale ||= params[:locale] || I18n.default_locale
  end
end

app/controllers/concerns/exception_handler.rb
# Productsコントローラの例外処理
module ExceptionHandler
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound do |e|
      json_response({ message: e.message }, :not_found)
    end

    rescue_from ActiveRecord::RecordInvalid do |e|
      json_response({ message: e.message }, :unprocessable_entity)
    end
  end
end

app/controllers/concerns/response.rb
module Response
  def json_response(object, status = :ok)
    render json: object, status: status
  end
end

app/controllers/daily_aggregations_controller.rb
require 'json'

class DailyAggregationsController < ApplicationController
  # 一覧(全件取得・検索)
  def index
    @q = DailyAggregation.ransack(params[:q])
    @daily_aggregations = @q.result(distinct: true)
  end

  # 詳細(取得)
  def show
    @daily_aggregation = DailyAggregation.find(params[:id])

    # 商品情報(ids)を配列に変換
    ids_to_array = JSON.parse(@daily_aggregation["products_ids"])
    @products = Product.with_deleted.where(id: ids_to_array)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    @@api_uri = '/api/products'

    before_action :encode_image_with_base64, only: [:create, :update]

    # 検索(全件取得)
    def index
      @products = Product.new.get_data(@@api_uri)
    end

    # 検索(取得)
    def show
      @product = Product.new.get_data(get_uri_with_id)
    end

    # 登録画面
    def new
      @product = Product.new
    end

    # 編集画面
    def edit
      @product = Product.find(params[:id])
    end

    # 登録
    def create
      @product = Product.new.post_data(@@api_uri, get_options)
      redirect_to products_path
    end

    # 変更
    def update
      @product = Product.new.put_data(get_uri_with_id, get_options)
      redirect_to products_path
    end

    # 削除
    def destroy
      @product = Product.new.delete_data(get_uri_with_id)
      redirect_to products_path
    end

    private
    def get_uri_with_id
      return @@api_uri + "/#{params[:id]}"
    end

    def encode_image_with_base64
      file = params[:product][:image]
      if file.present?
        params[:product][:image] = "data:" + file.content_type + ";base64," + Base64.encode64(File.read(file.path))
      end
    end

    def get_options
      return options = {
                        :body => params[:product].to_json,
                        :headers => { 'Content-Type' => 'application/json' }
                      }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/daily_aggregations_helper.rb
module DailyAggregationsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/daily_aggregations/index.html.erb
<h1><%= t(:aggregation_result) + t(:list) %></h1>

<p>
  <%= search_form_for @q do |f| %>
    <%= f.label 'From:' %>
    <%= f.date_field :date_gteq %>

    <%= f.label 'To:' %>
    <%= f.date_field :date_lteq %>

    <%= f.submit %>
  <% end %>
</p>

<table>
  <tr>
    <th>No.</th>
    <th><%= t(:date) %></th>
    <th><%= t(:sort) %></th>
    <th><%= t(:product_count) %></th>
  </tr>
  <%
    row_num = 1
    @daily_aggregations.each do |daily_aggregation|
  %>
    <tr>
      <td><%= row_num %></td>
      <td><%= daily_aggregation["date"] %></td>
      <td><%= daily_aggregation["sort"] %></td>
      <td><%= daily_aggregation["products_count"] %></td>
      <td>
        <%= link_to_if(daily_aggregation["products_count"] != 0,
            t(:show), daily_aggregation_path(daily_aggregation["id"])) {} %>
      </td>
    </tr>
  <%
      row_num += 1
    end
  %>
</table>

app/views/daily_aggregations/show.html.erb
<h3><%= "#{@daily_aggregation.date} [#{@daily_aggregation.sort}] #{t(:product_info)}#{t(:list)}"%></h3>

<table>
  <tr>
    <th>No.</th>
    <th><%= t(:product_title) %></th>
    <th><%= t(:product_image) %></th>
    <th><%= t(:description) %></th>
    <th><%= t(:price) %></th>
  </tr>
  <%
    row_num = 1
    @products.each do |product|
   %>
    <tr>
      <td><%= row_num %></td>
      <td><%= product["title"] %></td>
      <td><%= product["image"] %></td>
      <td><%= product["description"] %></td>
      <td><%= product["price"] %></td>
    </tr>
   <%
      row_num += 1
    end
   %>
</table>

<%= link_to t(:back), daily_aggregations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductsApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <p>
    <%= f.label :title, t(:product_title) %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :image, t(:product_image) %><br>
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.label :description, t(:description) %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :price, t(:price) %><br>
    <%= f.text_field :price %>
  </p>

  <p>
    <%= f.submit %>
  </p>

  <% end %>

app/views/products/edit.html.erb
<h1><%= t(:product_info) + t(:edit) %></h1>

<%= t(:before_product_image) %>：<%= @product.image %><br>
<%= render 'form' %>

<%= link_to t(:back), products_path %>

app/views/products/index.html.erb
<h1><%= t(:product_info) + t(:list) %></h1>

<p><%= link_to t(:create), new_product_path %></p>

<table>
  <tr>
    <th><%= t(:product_title) %></th>
    <th><%= t(:price) %></th>
  </tr>
  <tr>
    <% @products.each do |product| %>
      <tr>
        <td><%= product["title"] %></td>
        <td><%= product["price"] %></td>
        <td><%= link_to t(:show), product_path(product["id"]) %></td>
        <td><%= link_to t(:edit), edit_product_path(product["id"]) %></td>
        <td><%= link_to t(:delete), product_path(product["id"]),
                method: :delete,
                data: { confirm: t(:confirm_msg) } %></td>
      </tr>
    <% end %>
  </tr>
</table>

app/views/products/new.html.erb
<h1><%= t(:product_info) + t(:create) %></h1>

<%= render 'form' %>

<%= link_to t(:back), products_path %>

app/views/products/show.html.erb
<p>
  <strong><%= t(:product_title) %>:</strong>
  <%= @product["title"] %>
</p>

<p>
  <strong><%= t(:product_image) %>:</strong>
  <img src="<%= @product["image"]["url"] %>">
</p>

<p>
  <strong><%= t(:description) %>:</strong>
  <%= @product["description"] %>
</p>

<p>
  <strong><%= t(:price) %>:</strong>
  <%= @product["price"] %>
</p>

<%= link_to t(:back), products_path %>